---

- hosts: www
  remote_user: joaodias
  become: yes
  become_user: root
  order: sorted
  tasks:
  - name: Remocao de pacotes
    yum:
      name: "{{packages}}"
      state: absent
    vars:
      packages:
       - nginx
       - httpd
  - name: Instalacao de pacotes
    yum:
      name: "{{packages}}"
      state: latest
    vars:
      packages:
       - nmap
       - tcpdump
       - vim

...
