---

# Update Red Hat Like

- name: Update System Red Hat
  yum: name=* state=latest security=yes
  when: ansible_distribution_file_variety == 'CentOS' or ansible_distribution_file_variety == 'RedHat'

# Update Debian Like
- name: Update System Debian
  apt: update_cache=yes upgrade=yes
  when: ansible_distribution_file_variety == 'Debian' or ansible_distribution_file_variety == 'Ubuntu'
...
