---

- name: EC2 | Creating new instance
  ec2:
    #aws_access_key:
    #aws_secret_key:
    key_name: "{{ keypair }}"
    instance_type: "{{ type }}"
    image: ami-02eac2c0129f6376b
    group_id: "{{ sg }}"
    count: "{{ count }}"
    vpc_subnet_id: "{{ subnet }}"
    region: us-east-1
    assign_public_ip: "{{ public_ip }}"
    monitoring: yes
    instance_tags:
      Name: "{{ tag_name }}"
      Ambiente: "{{ tag_ambiente }}"
    termination_protection: yes

- name: EC2 | Getting Instance Info
  ec2_instance_info:
    filters:
      "tag:Name": "{{ tag_name }}"
  register: ec2info

- name: EC2 | Get IP Address
  shell: echo "{{ ec2info.instances|map(attribute='private_ip_address')|list }}" | cut -d "'" -f 2
  register: ec2ip

- name: EC2 | Get EC2 IP Address
  debug: msg={{ ec2ip.stdout }}

...
